import Foundation
import FoundationModels

struct MessageGenerator {
    enum GeneratorError: LocalizedError {
        case unavailable(String)
        case unableToGenerate(String)
        case outOfContext

        var errorDescription: String? {
            switch self {
            case .unavailable(let message):
                return "Apple Foundation Model is unavailable: \(message)"
            case .unableToGenerate(let message):
                return "Unable to generate message: \(message)"
            case .outOfContext:
                return "Your git diff is too large to be analyzed"
            }
        }
    }

    func generateCommitMessage(diff: String, lang: CommitLanguage) async throws
        -> String
    {
        let model = SystemLanguageModel.default

        guard case .available = model.availability else {
            throw GeneratorError.unavailable(
                String(describing: model.availability)
            )
        }

        let prompt = """
            You are an expert Git commit message generator.

            Analyze the following Git diff and generate a clean commit message.

            Rules:

            1. Follow the Conventional Commits specification.
            2. The first line must use exactly this format:

               type(scope): message

            3. Use one of these commit types:
               - feat: a new feature
               - fix: a bug fix
               - refactor: a code change that neither fixes a bug nor adds a feature
               - docs: documentation changes
               - test: adding or updating tests
               - chore: maintenance tasks
               - build: build system or dependency changes
               - ci: continuous integration changes
               - perf: performance improvements
               - style: formatting or code-style changes

            4. Use a short, precise and imperative subject.
            5. Do not end the subject with a period.
            6. Use a lowercase type and scope.
            7. Add a scope when it can be determined from the diff.
            8. Add a body only when it provides useful additional information.
            9. Each body line must start with "- ".
            10. If the change introduces a breaking change:
                - Add "!" after the scope, before the colon.
                - Add a final footer using exactly this format:

                  BREAKING CHANGE: Description of the breaking change

            11. Do not invent information that is not present in the diff.
            12. Do not include Markdown fences, explanations or introductory text.
            13. Return only the commit message.
            14. Write the commit message in this language: \(lang.displayName)

            Expected format:

            type(scope): message
            - Description
            - Description
            - Description

            For a breaking change:

            type(scope)!: message
            - Description

            BREAKING CHANGE: Description of the breaking change

            Git diff:

            \(diff)
            """

        let maxTokenContextSize = model.contextSize

        let promptTokenSize: Int

        if #available(macOS 26.4, *) {
            promptTokenSize = try await model.tokenCount(for: prompt)
        } else {
            throw GeneratorError.unavailable(
                "Token counting requires macOS 26.4 or newer"
            )
        }

        let reservedOutputTokens = 512

        guard promptTokenSize + reservedOutputTokens <= maxTokenContextSize
        else {
            throw GeneratorError.outOfContext
        }

        let session = LanguageModelSession(model: model)

        do {
            let response = try await session.respond(to: prompt)
            return response.content + "\n\nGenerated by kaumite"
        } catch {
            throw GeneratorError.unableToGenerate(error.localizedDescription)
        }
    }
}
